### ISSUE TITLE
SDK link is broken

### ISSUE THREAD

**Issue by jmenashe** [laobubu/SynapticsPen#1]
The SDK link in your readme is broken. Is there another way to get the SDK from Synaptics?

**Comment by EXPLOR3R** [comment]
Synaptics recently redesigned their website and seems like the SDK file is no longer on their website. 
I just upload the full SDK zip file I downloaded last year. You can find it here: `http://bit.ly/2fiLdfH`

**Comment by jmenashe** [comment]
Awesome, thank you for the link and the quick response!
